### PR TITLE
Focus on the HTML portion of a svelte document

### PR DESCRIPTION
**Pull request by segovo**
Jumps to the end of the script tags to show where the html would usually be

### CODE REVIEW

**Comment by K-Sato1995** [comment]
@segovo 

Thank you for creating a PR!:)
I'll look into it as soon as i get some freetime!:)

**Review by K-Sato1995 — APPROVED** [review]
Looks good to me ! Thank you !

**Comment by K-Sato1995** [comment]
@segovo 

published it😄


https://marketplace.visualstudio.com/items?itemName=K-Sato.svelte-tag-focuser

**Comment by segovo** [comment]
So sweet!! Thanks for making this

**Pull request merged**
